library: Dylan
unique-id-base: 0
Files: bootstrap
       macros
       macros-iteration
       exports
       object
       misc
       boolean
       cmp
       type
       class
       designator-class
       copy
       func
       activation-record
       num
       bignum
       ratio
       rawptr
       machineword
       symbol
       char
       value-cell
       collection
       array
       vector
       stretchy
       string
       buffer
       list
       range
       deque
       table
       set
       sort
       limited-collection
       seals
       handler
       nlx
       output
       condition
       debug
       thread-single
       synchronization
       synchronization-single
       system
       main
       probes
